# Generated by Django 4.0.4 on 2022-05-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postavshiki',
            name='kod_postavshika',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Код поставщика'),
        ),
    ]
