# Generated by Django 4.0.4 on 2022-05-05 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_postavshiki_kod_postavshika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicioneri',
            name='data_proizvodstva',
            field=models.DateField(verbose_name='Дата производства'),
        ),
        migrations.AlterField(
            model_name='condicioneri',
            name='garantia',
            field=models.IntegerField(verbose_name='Гарантия'),
        ),
        migrations.AlterField(
            model_name='condicioneri',
            name='kod_proizvoditelya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.proizvoditeli', verbose_name='Код производителя'),
        ),
        migrations.AlterField(
            model_name='condicioneri',
            name='kod_prostavshika',
            field=models.ManyToManyField(to='main.postavshiki', verbose_name='Код поставщика'),
        ),
        migrations.AlterField(
            model_name='condicioneri',
            name='naimenovanie',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='condicioneri',
            name='nalichie',
            field=models.BooleanField(default=True, verbose_name='Наличие'),
        ),
        migrations.AlterField(
            model_name='condicioneri',
            name='nomer_partii',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.postavki', verbose_name='Номер партии'),
        ),
        migrations.AlterField(
            model_name='condicioneri',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='condicioneri',
            name='seriyni_nomer',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='pokupatel',
            name='FIO_pokupatelya',
            field=models.CharField(max_length=150, verbose_name='ФИО покупателя'),
        ),
        migrations.AlterField(
            model_name='pokupatel',
            name='nomer_pokupatelya',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер покупателя'),
        ),
        migrations.AlterField(
            model_name='postavki',
            name='data_postavki',
            field=models.DateField(verbose_name='Дата поставки'),
        ),
        migrations.AlterField(
            model_name='postavki',
            name='kod_postavshika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.postavshiki', verbose_name='Код поставщика'),
        ),
        migrations.AlterField(
            model_name='postavki',
            name='nomer_partii',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер партии'),
        ),
        migrations.AlterField(
            model_name='postavki',
            name='price_zakupki',
            field=models.PositiveIntegerField(verbose_name='Цена закупки'),
        ),
        migrations.AlterField(
            model_name='postavshiki',
            name='naimenovanie_postavshika',
            field=models.CharField(max_length=100, verbose_name='Наименование поставщика'),
        ),
        migrations.AlterField(
            model_name='postavshiki',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='postavshiki',
            name='uridicheski_adress',
            field=models.CharField(max_length=100, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='privoz',
            name='kolichestvo',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='privoz',
            name='nomer_partii',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.postavki', verbose_name='Номер партии'),
        ),
        migrations.AlterField(
            model_name='privoz',
            name='seriyni_nomer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.condicioneri', verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='prodaji',
            name='data',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='prodaji',
            name='nomer_cheka',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер чека'),
        ),
        migrations.AlterField(
            model_name='prodaji',
            name='tabelniy_nomer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sotrudniki', verbose_name='Табельный номер'),
        ),
        migrations.AlterField(
            model_name='proizvoditeli',
            name='kod_proizvoditelya',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Код производителя'),
        ),
        migrations.AlterField(
            model_name='proizvoditeli',
            name='naimenovanie_proizvoditelya',
            field=models.CharField(max_length=100, verbose_name='Наименование производителя'),
        ),
        migrations.AlterField(
            model_name='proizvoditeli',
            name='uridicheskiy_adress',
            field=models.CharField(max_length=150, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='realizacia',
            name='kolichestvo',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='realizacia',
            name='nomer_cheka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.prodaji', verbose_name='Номер чека'),
        ),
        migrations.AlterField(
            model_name='realizacia',
            name='seriyni_nomer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.condicioneri', verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='schet_pokupatelya',
            name='nomer_pokupatelya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pokupatel', verbose_name='Номер покупателя'),
        ),
        migrations.AlterField(
            model_name='schet_pokupatelya',
            name='nomer_scheta',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер счета'),
        ),
        migrations.AlterField(
            model_name='schet_pokupatelya',
            name='sostoyanie_scheta',
            field=models.PositiveIntegerField(verbose_name='Состояние счета'),
        ),
        migrations.AlterField(
            model_name='sotrudniki',
            name='FIO',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='sotrudniki',
            name='doljnost',
            field=models.CharField(max_length=150, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='sotrudniki',
            name='tabelniy_nomer',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Табельный номер'),
        ),
        migrations.AlterField(
            model_name='zavoz',
            name='kod_postavshika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.postavshiki', verbose_name='Код поставщика'),
        ),
        migrations.AlterField(
            model_name='zavoz',
            name='nomer_partii',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.postavki', verbose_name='Номер партии'),
        ),
        migrations.AlterField(
            model_name='zavoz',
            name='seriyni_nomer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.condicioneri', verbose_name='Серийный номер'),
        ),
    ]
