# Generated by Django 4.0.4 on 2022-05-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_condicioneri_data_proizvodstva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicioneri',
            name='price',
            field=models.CharField(max_length=100, verbose_name='Цена'),
        ),
    ]
