# Generated by Django 4.0.4 on 2022-05-16 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_condicioneri_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokupatel',
            options={'verbose_name': 'Покупатель', 'verbose_name_plural': 'Покупатели'},
        ),
    ]
