# Generated by Django 4.0.4 on 2022-05-16 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_pokupatel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condicioneri',
            options={'verbose_name': 'Кондиционер', 'verbose_name_plural': 'Кондиционеры'},
        ),
        migrations.AlterModelOptions(
            name='postavki',
            options={'verbose_name': 'Поставка', 'verbose_name_plural': 'Постравки'},
        ),
        migrations.AlterModelOptions(
            name='postavshiki',
            options={'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AlterModelOptions(
            name='privoz',
            options={'verbose_name': 'Привоз', 'verbose_name_plural': 'Привозы'},
        ),
        migrations.AlterModelOptions(
            name='prodaji',
            options={'verbose_name': 'Продажа', 'verbose_name_plural': 'Продажи'},
        ),
        migrations.AlterModelOptions(
            name='proizvoditeli',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterModelOptions(
            name='realizacia',
            options={'verbose_name': 'Реализация', 'verbose_name_plural': 'Рализации'},
        ),
        migrations.AlterModelOptions(
            name='schet_pokupatelya',
            options={'verbose_name': 'Счет покупателя', 'verbose_name_plural': 'Счета покупателей'},
        ),
        migrations.AlterModelOptions(
            name='sotrudniki',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='zavoz',
            options={'verbose_name': 'Завоз', 'verbose_name_plural': 'Завозы'},
        ),
    ]
